//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polygons.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Polygons.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE maguiss
        ///go
        ///
        ///create schema polygon
        ///go.
        /// </summary>
        internal static string _00_0___SQL_CREATE_SCHEMA_Polygon {
            get {
                return ResourceManager.GetString("_00_0___SQL_CREATE_SCHEMA_Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE maguiss
        ///GO
        ///
        ///IF EXISTS(Select name from sys.objects where object_id = object_id(&apos;polygon.users&apos;)) DROP TABLE polygon.users
        ///GO
        ///
        ///CREATE TABLE [polygon].[users](
        ///	 [id]				[int]			IDENTITY(0,1) UNIQUE NOT NULL
        ///	,[username]			[nvarchar](40)	NOT NULL
        ///	,[pwd]				[varbinary](32)	NULL
        ///	,[information]		[nvarchar](500)	NULL
        ///	,[dateCreate]		datetime		default current_timestamp
        ///	,[dateLastLogin]	datetime 
        ///	,[loginSuccessful]	tinyint			default 0
        ///	,[sessionID]		int				
        ///
        /// CONSTRAINT [PK_MyUsers] PRIMARY  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _01_0___SQL_CREATE_TABLE_polygon_users_and_populate {
            get {
                return ResourceManager.GetString("_01_0___SQL_CREATE_TABLE_polygon_users_and_populate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE MAGUISS
        ///GO
        ///
        ///if not exists (select name from sys.objects where name = &apos;sessionID&apos; and schema_id = schema_id(&apos;polygon&apos;))
        ///create table polygon.sessionID (
        ///	sessionID int identity (0,1),
        ///	username nvarchar(40)
        ///)
        ///
        ///SELECT * from polygon.sessionID.
        /// </summary>
        internal static string _01_1_SQL_CREATE_TABLE_polygon_sessionID {
            get {
                return ResourceManager.GetString("_01_1_SQL_CREATE_TABLE_polygon_sessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use maguiss
        ///go
        ///-- ================================================
        ///-- Template generated from Template Explorer using:
        ///-- Create Scalar Function (New Menu).SQL
        ///--
        ///-- Use the Specify Values for Template Parameters 
        ///-- command (Ctrl-Shift-M) to fill in the parameter 
        ///-- values below.
        ///--
        ///-- This block of comments will not be included in
        ///-- the definition of the function.
        ///-- ================================================
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- ==================== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _02_0___SQL_CREATE_FUNCTION_stringToPassword {
            get {
                return ResourceManager.GetString("_02_0___SQL_CREATE_FUNCTION_stringToPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ================================================
        ///-- Template generated from Template Explorer using:
        ///-- Create Scalar Function (New Menu).SQL
        ///--
        ///-- Use the Specify Values for Template Parameters 
        ///-- command (Ctrl-Shift-M) to fill in the parameter 
        ///-- values below.
        ///--
        ///-- This block of comments will not be included in
        ///-- the definition of the function.
        ///-- ================================================
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- ===================================== [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _02_1_CREATE_FUNCTION_polygon_getNextSessionID {
            get {
                return ResourceManager.GetString("_02_1_CREATE_FUNCTION_polygon_getNextSessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE maguiss
        ///GO
        ///
        ///-- ================================================
        ///-- Template generated from Template Explorer using:
        ///-- Create Procedure (New Menu).SQL
        ///--
        ///-- Use the Specify Values for Template Parameters 
        ///-- command (Ctrl-Shift-M) to fill in the parameter 
        ///-- values below.
        ///--
        ///-- This block of comments will not be included in
        ///-- the definition of the procedure.
        ///-- ================================================
        ///SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///-- ======================= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _03_0___SQL_CREATE_PROCEDURE_usp_userLoginSuccessful {
            get {
                return ResourceManager.GetString("_03_0___SQL_CREATE_PROCEDURE_usp_userLoginSuccessful", resourceCulture);
            }
        }
    }
}
